/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AnalizadorLexico;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author danil
 */
public class MiniSQL extends javax.swing.JFrame {

    /**
     * Creates new form MiniSQL
     */
    String PathSQL = "";
    
    public MiniSQL() {
        initComponents();
        //btn_Escanear.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_elegirArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ChosenPath = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btn_Escanear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea_Errores = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_elegirArchivo.setBackground(new java.awt.Color(0, 0, 0));
        btn_elegirArchivo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        btn_elegirArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btn_elegirArchivo.setText("Examinar");
        btn_elegirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elegirArchivoActionPerformed(evt);
            }
        });

        txt_ChosenPath.setEditable(false);
        txt_ChosenPath.setFont(new java.awt.Font("Tempus Sans ITC", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(txt_ChosenPath);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jLabel1.setText("elegir archivo con código Mini-SQL");

        btn_Escanear.setBackground(new java.awt.Color(0, 153, 51));
        btn_Escanear.setFont(new java.awt.Font("Segoe WP SemiLight", 1, 11)); // NOI18N
        btn_Escanear.setText("Escanear");
        btn_Escanear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_EscanearFocusGained(evt);
            }
        });
        btn_Escanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EscanearActionPerformed(evt);
            }
        });

        txtArea_Errores.setColumns(20);
        txtArea_Errores.setRows(5);
        jScrollPane2.setViewportView(txtArea_Errores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_elegirArchivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btn_Escanear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_elegirArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btn_Escanear)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_elegirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elegirArchivoActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Mini-SQL", "sql", "sql");
        jf.setFileFilter(filter);
        int r = jf.showOpenDialog(null);
        if(r==JFileChooser.APPROVE_OPTION){
            File f = jf.getSelectedFile();
            PathSQL = f.getAbsolutePath();
            txt_ChosenPath.setText(PathSQL);
            btn_Escanear.setVisible(true);
        }
    }//GEN-LAST:event_btn_elegirArchivoActionPerformed

    private void btn_EscanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EscanearActionPerformed
        // TODO add your handling code here:
        //btn_Escanear.setVisible(false);
        txtArea_Errores.setText("");
        
    }//GEN-LAST:event_btn_EscanearActionPerformed

    private void btn_EscanearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_EscanearFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EscanearFocusGained

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Escanear;
    private javax.swing.JButton btn_elegirArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea_Errores;
    private javax.swing.JTextPane txt_ChosenPath;
    // End of variables declaration//GEN-END:variables
}
